In [1]:
import numpy as np
import pandas as pd
data=pd.read_csv("pima-indians-diabetes.csv",names=['preg','plas','pres','skin','test','mas','pedi','age','class'])
data

preg  plas  pres  skin  test   mas   pedi  age  class
0       6   148    72    35     0  33.6  0.627   50      1
1       1    85    66    29     0  26.6  0.351   31      0
2       8   183    64     0     0  23.3  0.672   32      1
3       1    89    66    23    94  28.1  0.167   21      0
4       0   137    40    35   168  43.1  2.288   33      1
..    ...   ...   ...   ...   ...   ...    ...  ...    ...
763    10   101    76    48   180  32.9  0.171   63      0
764     2   122    70    27     0  36.8  0.340   27      0
765     5   121    72    23   112  26.2  0.245   30      0
766     1   126    60     0     0  30.1  0.349   47      1
767     1    93    70    31     0  30.4  0.315   23      0

[768 rows x 9 columns]

In [2]:
(data['skin']==0).sum()


227

In [3]:
data.replace({'test': 0, 'skin': 0}, np.nan, inplace=True)

In [4]:
# data.replace({'test':0,'skin':0},np.NAN,inplace=True)
from sklearn.impute import KNNImputer

imputer = KNNImputer(n_neighbors=3)
data = imputer.fit_transform(data)

data

array([[  6.   , 148.   ,  72.   , ...,   0.627,  50.   ,   1.   ],
       [  1.   ,  85.   ,  66.   , ...,   0.351,  31.   ,   0.   ],
       [  8.   , 183.   ,  64.   , ...,   0.672,  32.   ,   1.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,   0.245,  30.   ,   0.   ],
       [  1.   , 126.   ,  60.   , ...,   0.349,  47.   ,   1.   ],
       [  1.   ,  93.   ,  70.   , ...,   0.315,  23.   ,   0.   ]])

In [5]:
data=data[:,:-1]
data_o=data
data_o2=data
data_o3=data
data_o4=data

In [6]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler(feature_range=(0,1))
data_o=scaler.fit_transform(data_o)
data_o

array([[0.35294118, 0.74371859, 0.59016393, ..., 0.50074516, 0.23441503,
        0.48333333],
       [0.05882353, 0.42713568, 0.54098361, ..., 0.39642325, 0.11656704,
        0.16666667],
       [0.47058824, 0.91959799, 0.52459016, ..., 0.34724292, 0.25362938,
        0.18333333],
       ...,
       [0.29411765, 0.6080402 , 0.59016393, ..., 0.390462  , 0.07130658,
        0.15      ],
       [0.05882353, 0.63316583, 0.49180328, ..., 0.4485842 , 0.11571307,
        0.43333333],
       [0.05882353, 0.46733668, 0.57377049, ..., 0.45305514, 0.10119556,
        0.03333333]])

In [7]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
data_o2=scaler.fit_transform(data_o2)
data_o2

array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.20401277,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.68442195,
        -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -1.10325546,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.73518964,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.24020459,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.20212881,
        -0.47378505, -0.87137393]])

In [8]:
from sklearn.preprocessing import Normalizer
norm = Normalizer()
data_o3 = norm.fit_transform(data_o3)
data_o3

array([[0.02747592, 0.67773925, 0.32971099, ..., 0.15386513, 0.00287123,
        0.22896596],
       [0.00734498, 0.62432312, 0.48476854, ..., 0.19537641, 0.00257809,
        0.22769432],
       [0.02861868, 0.65465224, 0.22894942, ..., 0.0833519 , 0.00240397,
        0.11447471],
       ...,
       [0.02691539, 0.65135243, 0.38758161, ..., 0.14103664, 0.00131885,
        0.16149234],
       [0.00510304, 0.64298251, 0.30618215, ..., 0.15360138, 0.00178096,
        0.23984268],
       [0.00690756, 0.64240313, 0.48352924, ..., 0.20998984, 0.00217588,
        0.15887389]])

In [9]:
np.sum(data_o3[0]**2)

0.9999999999999998

In [10]:
from sklearn.preprocessing import Binarizer
binarizer = Binarizer(threshold=0.0)
data_b = binarizer.fit_transform(data_o4)
print(data_b)

[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]


In [12]:
data_a=np.concatenate((data,data_o,data_o2,data_o3,data_o4,data_b),axis=1)

In [15]:
print(data_a[0])

[ 6.00000000e+00  1.48000000e+02  7.20000000e+01  3.50000000e+01
  1.25333333e+02  3.36000000e+01  6.27000000e-01  5.00000000e+01
  3.52941176e-01  7.43718593e-01  5.90163934e-01  3.04347826e-01
  1.33814103e-01  5.00745156e-01  2.34415030e-01  4.83333333e-01
  6.39947260e-01  8.48323795e-01  1.49640753e-01  6.25703208e-01
 -2.69421175e-01  2.04012771e-01  4.68491977e-01  1.42599540e+00
  2.74759155e-02  6.77739248e-01  3.29710985e-01  1.60276173e-01
  5.73941345e-01  1.53865127e-01  2.87123316e-03  2.28965962e-01
  6.00000000e+00  1.48000000e+02  7.20000000e+01  3.50000000e+01
  1.25333333e+02  3.36000000e+01  6.27000000e-01  5.00000000e+01
  1.00000000e+00  1.00000000e+00  1.00000000e+00  1.00000000e+00
  1.00000000e+00  1.00000000e+00  1.00000000e+00  1.00000000e+00]
