In this dataset, there is information about the health of women regarding diabetes. Initially, I observed that the dataset lacks column names. To address this, I assigned appropriate column names when reading the CSV file.

Next, I identified cells with null values. However, I also noticed some zero values in the 'test' and 'skin' features. It is apparent that certain information was not entered, possibly due to a lack of tools for data input by some individuals. To handle this, I initially replaced zero values with np.nan (NumPy's representation of missing values).

Following that, I replaced the np.nan values with the mean values of the 'test' and 'skin' features. Alternatively, I employed the KNN (K-Nearest Neighbors) method for imputation. In the final step, data scaling to a range of 0 to 1 was performed using the Min-Max Scaler. Subsequently, the Standard Scaler was applied after the Min-Max Scaler. The choice between Standard Scaler and Min-Max Scaler can be made based on experience and AB testing.

In [1]:
import numpy as np 
import pandas as pd 
data=pd.read_csv('pima-indians-diabetes.csv',names=['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class'])
data

preg  plas  pres  skin  test  mass   pedi  age  class
0       6   148    72    35     0  33.6  0.627   50      1
1       1    85    66    29     0  26.6  0.351   31      0
2       8   183    64     0     0  23.3  0.672   32      1
3       1    89    66    23    94  28.1  0.167   21      0
4       0   137    40    35   168  43.1  2.288   33      1
..    ...   ...   ...   ...   ...   ...    ...  ...    ...
763    10   101    76    48   180  32.9  0.171   63      0
764     2   122    70    27     0  36.8  0.340   27      0
765     5   121    72    23   112  26.2  0.245   30      0
766     1   126    60     0     0  30.1  0.349   47      1
767     1    93    70    31     0  30.4  0.315   23      0

[768 rows x 9 columns]

In [2]:
data

preg  plas  pres  skin  test  mass   pedi  age  class
0       6   148    72    35     0  33.6  0.627   50      1
1       1    85    66    29     0  26.6  0.351   31      0
2       8   183    64     0     0  23.3  0.672   32      1
3       1    89    66    23    94  28.1  0.167   21      0
4       0   137    40    35   168  43.1  2.288   33      1
..    ...   ...   ...   ...   ...   ...    ...  ...    ...
763    10   101    76    48   180  32.9  0.171   63      0
764     2   122    70    27     0  36.8  0.340   27      0
765     5   121    72    23   112  26.2  0.245   30      0
766     1   126    60     0     0  30.1  0.349   47      1
767     1    93    70    31     0  30.4  0.315   23      0

[768 rows x 9 columns]

In [3]:
data.isna().sum()

preg     0
plas     0
pres     0
skin     0
test     0
mass     0
pedi     0
age      0
class    0
dtype: int64

In [4]:
data.isnull().sum()

preg     0
plas     0
pres     0
skin     0
test     0
mass     0
pedi     0
age      0
class    0
dtype: int64

In [10]:
skin_mean=data[data['skin']!=0]['skin'].mean()

In [11]:
skin_mean

29.153419593345657

In [14]:
data.replace({'skin':0},skin_mean,inplace=True)

In [15]:
data

preg  plas  pres      skin  test  mass   pedi  age  class
0       6   148    72  35.00000     0  33.6  0.627   50      1
1       1    85    66  29.00000     0  26.6  0.351   31      0
2       8   183    64  29.15342     0  23.3  0.672   32      1
3       1    89    66  23.00000    94  28.1  0.167   21      0
4       0   137    40  35.00000   168  43.1  2.288   33      1
..    ...   ...   ...       ...   ...   ...    ...  ...    ...
763    10   101    76  48.00000   180  32.9  0.171   63      0
764     2   122    70  27.00000     0  36.8  0.340   27      0
765     5   121    72  23.00000   112  26.2  0.245   30      0
766     1   126    60  29.15342     0  30.1  0.349   47      1
767     1    93    70  31.00000     0  30.4  0.315   23      0

[768 rows x 9 columns]

In [16]:
test_mean=data[data['test']!=0]['test'].mean()

In [19]:
test_mean

155.5482233502538

In [20]:
data.replace({'test':0},test_mean,inplace=True)

In [21]:
data

preg  plas  pres      skin        test  mass   pedi  age  class
0       6   148    72  35.00000  155.548223  33.6  0.627   50      1
1       1    85    66  29.00000  155.548223  26.6  0.351   31      0
2       8   183    64  29.15342  155.548223  23.3  0.672   32      1
3       1    89    66  23.00000   94.000000  28.1  0.167   21      0
4       0   137    40  35.00000  168.000000  43.1  2.288   33      1
..    ...   ...   ...       ...         ...   ...    ...  ...    ...
763    10   101    76  48.00000  180.000000  32.9  0.171   63      0
764     2   122    70  27.00000  155.548223  36.8  0.340   27      0
765     5   121    72  23.00000  112.000000  26.2  0.245   30      0
766     1   126    60  29.15342  155.548223  30.1  0.349   47      1
767     1    93    70  31.00000  155.548223  30.4  0.315   23      0

[768 rows x 9 columns]

In [22]:
from sklearn.impute import KNNImputer
imputer=KNNImputer(n_neighbors=3)
imputer.fit_transform(data)


array([[  6.   , 148.   ,  72.   , ...,   0.627,  50.   ,   1.   ],
       [  1.   ,  85.   ,  66.   , ...,   0.351,  31.   ,   0.   ],
       [  8.   , 183.   ,  64.   , ...,   0.672,  32.   ,   1.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,   0.245,  30.   ,   0.   ],
       [  1.   , 126.   ,  60.   , ...,   0.349,  47.   ,   1.   ],
       [  1.   ,  93.   ,  70.   , ...,   0.315,  23.   ,   0.   ]])

In [23]:
import sys
np.set_printoptions(threshold=sys.maxsize)
print(data)

     preg  plas  pres      skin        test  mass   pedi  age  class
0       6   148    72  35.00000  155.548223  33.6  0.627   50      1
1       1    85    66  29.00000  155.548223  26.6  0.351   31      0
2       8   183    64  29.15342  155.548223  23.3  0.672   32      1
3       1    89    66  23.00000   94.000000  28.1  0.167   21      0
4       0   137    40  35.00000  168.000000  43.1  2.288   33      1
..    ...   ...   ...       ...         ...   ...    ...  ...    ...
763    10   101    76  48.00000  180.000000  32.9  0.171   63      0
764     2   122    70  27.00000  155.548223  36.8  0.340   27      0
765     5   121    72  23.00000  112.000000  26.2  0.245   30      0
766     1   126    60  29.15342  155.548223  30.1  0.349   47      1
767     1    93    70  31.00000  155.548223  30.4  0.315   23      0

[768 rows x 9 columns]


In [24]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler(feature_range=(0,1))
data=scaler.fit_transform(data)


In [25]:
data

array([[0.35294118, 0.74371859, 0.59016393, 0.30434783, 0.17013008,
        0.50074516, 0.23441503, 0.48333333, 1.        ],
       [0.05882353, 0.42713568, 0.54098361, 0.23913043, 0.17013008,
        0.39642325, 0.11656704, 0.16666667, 0.        ],
       [0.47058824, 0.91959799, 0.52459016, 0.24079804, 0.17013008,
        0.34724292, 0.25362938, 0.18333333, 1.        ],
       [0.05882353, 0.44723618, 0.54098361, 0.17391304, 0.09615385,
        0.41877794, 0.03800171, 0.        , 0.        ],
       [0.        , 0.68844221, 0.32786885, 0.30434783, 0.18509615,
        0.64232489, 0.94363792, 0.2       , 1.        ],
       [0.29411765, 0.58291457, 0.60655738, 0.24079804, 0.17013008,
        0.38152012, 0.05251921, 0.15      , 0.        ],
       [0.17647059, 0.3919598 , 0.40983607, 0.27173913, 0.08894231,
        0.46199702, 0.07258753, 0.08333333, 1.        ],
       [0.58823529, 0.57788945, 0.        , 0.24079804, 0.17013008,
        0.52608048, 0.02391119, 0.13333333, 0.        ],


In [26]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
data=scaler.fit_transform(data)

In [27]:
data

array([[ 6.39947260e-01,  8.48323795e-01,  1.49640753e-01,
         6.65502121e-01, -2.71787659e-16,  2.04012771e-01,
         4.68491977e-01,  1.42599540e+00,  1.36589591e+00],
       [-8.44885053e-01, -1.12339636e+00, -1.60545747e-01,
        -1.74633816e-02, -2.71787659e-16, -6.84421946e-01,
        -3.65060778e-01, -1.90671905e-01, -7.32120209e-01],
       [ 1.23388019e+00,  1.94372388e+00, -2.63941247e-01,
         0.00000000e+00, -2.71787659e-16, -1.10325546e+00,
         6.04397318e-01, -1.05584152e-01,  1.36589591e+00],
       [-8.44885053e-01, -9.98207780e-01, -1.60545747e-01,
        -7.00428884e-01, -7.24388738e-01, -4.94043078e-01,
        -9.20762614e-01, -1.04154944e+00, -7.32120209e-01],
       [-1.14185152e+00,  5.04055196e-01, -1.50468724e+00,
         6.65502121e-01,  1.46550563e-01,  1.40974560e+00,
         5.48490910e+00, -2.04963989e-02,  1.36589591e+00],
       [ 3.42980797e-01, -1.53184856e-01,  2.53036252e-01,
         0.00000000e+00, -2.71787659e-16, -8.113411